/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    Counter: typeof import('./../../src/components/counter.vue')['default']
    Footer: typeof import('./../../src/components/footer.vue')['default']
    Header: typeof import('./../../src/components/header.vue')['default']
    'IIon:mdMicrophone': typeof import('~icons/ion/md-microphone')['default']
    'IMingcute:microphoneLine': typeof import('~icons/mingcute/microphone-line')['default']
    'IMingcute:voiceLine': typeof import('~icons/mingcute/voice-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./../../src/components/sider.vue')['default']
  }
}
