/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACarousel: typeof import('@arco-design/web-vue')['Carousel']
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AImage: typeof import('@arco-design/web-vue')['Image']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    Carousel: typeof import('./../../src/components/content/personalRecommend/carousel.vue')['default']
    Counter: typeof import('./../../src/components/counter.vue')['default']
    ExclusivePost: typeof import('./../../src/components/content/personalRecommend/exclusive-post.vue')['default']
    FindMusic: typeof import('./../../src/components/find-music.vue')['default']
    Footer: typeof import('./../../src/components/footer.vue')['default']
    Header: typeof import('./../../src/components/header.vue')['default']
    HiImage: typeof import('./../../src/components/hi-image/index.vue')['default']
    HiImageBar: typeof import('./../../src/components/hi-image-bar/index.vue')['default']
    HotPodcast: typeof import('./../../src/components/content/personalRecommend/hot-podcast.vue')['default']
    'IIc:roundPlayCircleOutline': typeof import('~icons/ic/round-play-circle-outline')['default']
    'IIon:mdMicrophone': typeof import('~icons/ion/md-microphone')['default']
    'IMingcute:microphoneLine': typeof import('~icons/mingcute/microphone-line')['default']
    'IMingcute:voiceLine': typeof import('~icons/mingcute/voice-line')['default']
    ListenBook: typeof import('./../../src/components/content/personalRecommend/listen-book.vue')['default']
    MyCustomization: typeof import('./../../src/components/content/my-customization.vue')['default']
    Newest: typeof import('./../../src/components/content/newest.vue')['default']
    NewestMusic: typeof import('./../../src/components/content/personalRecommend/newest-music.vue')['default']
    PersonalRecommend: typeof import('./../../src/components/content/personal-recommend.vue')['default']
    RankingList: typeof import('./../../src/components/content/ranking-list.vue')['default']
    RecommendMv: typeof import('./../../src/components/content/personalRecommend/recommend-mv.vue')['default']
    RecommendPlaylist: typeof import('./../../src/components/content/personalRecommend/recommend-playlist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./../../src/components/sider.vue')['default']
    SingerList: typeof import('./../../src/components/content/singer-list.vue')['default']
    SongList: typeof import('./../../src/components/content/song-list.vue')['default']
  }
}
